### ISSUE TITLE
Can beat tracking model be retrained based on audio

### ISSUE THREAD

**Issue by dianxin556** [Music-and-Culture-Technology-Lab/omnizart#33]
Is it possible to retrain the audio-based beat tracking model by replacing the input data or feature？Thanks！

**Comment by BreezeWhite** [comment]
Hi, I think it would be in a totally different scenario, since the current input data representation is in symbolic domain, and the feature is also build on this assumption. It is hence incompatible to directly change to use audio-based input. You could still use the predefined TF model and handcraft a new type of data representation that is based the audio input for the model. That would be a huge engineering however.
