### ISSUE TITLE
make install fails

### ISSUE THREAD

**Issue by hagenw** [Music-and-Culture-Technology-Lab/omnizart#37]
I first started by running (inside my virtual environment that I used before to run `omnizart`):

```bash
$ poetry install
$ python -m pytest
```
which results in errors as the checkpoint files are stored under `~/.local/.../site-packages/` as described in `CONTRIBUTING.md`.

I then switched to start from scratch by deactivating my virtual environment and running:

```bash
$ make install
```

but this fails with:

```
Installing the current project: omnizart (0.4.1)
./scripts/install.sh: line 109: omnizart: command not found
Makefile:57: recipe for target 'install' failed
make: *** [install] Error 127
```

**Comment by BreezeWhite** [comment]
I'm not sure whether you use `conda` or `python-venv` as your virtual environment. The command `poetry install` will create its own virtual environment if there is no `.venv` directory (which can be created by running `python -m venv .venv`). And if you are using `conda`, there could be conflict with `poetry`.

Could you also try running `./script/install.sh` directly, instead of `make install` and see what happens?

**Comment by hagenw** [comment]
I deleted the `.venv` folder and created it with
```bash
$ virtualenv .venv
```
Then I executed
```bash
$ ./scripts/install.sh
...
Installing the current project: omnizart (0.4.1)
./scripts/install.sh: line 109: omnizart: command not found
```

**Comment by hagenw** [comment]
I continued by running the following commands manually:

```bash
$ source .venv/bin/activate
$ omnizart download-checkpoints
```

But if I then start running the tests, they still fail, because `pytest` is not installed.

**Comment by BreezeWhite** [comment]
The first problem is caused by the existence of `.venv` directory, which will be automatically used by `poetry` while installing everything. And this behavior contradicts the original intention that by directly executing `./scripts/install.sh` without arguments, it should install dependencies on the system and will not activate the virtualenv during installation. This will broken at the line 109, which the `omnizart` is installed under `.venv`, but the installation is not using that virtualenv. The bug could be fixed by modifying the installation script I think, by adding `poetry config virtualenvs.in-project false` to line 54.

And for the missing package of `pytest`, it is defined as a development dependency, which should be manually installed by running `poetry install`. This is indicated in the last line of section `Download and install` in `CONTRIBUTING.md`.

**Comment by hagenw** [comment]
So the problem is that I named the virtual environment `.venv`?

I'm still wondering what a proper solution should/could be as the indicated way in `CONTRIBUTING.md` is not working for me.

**Comment by BreezeWhite** [comment]
According to the document of poetry [here](https://python-poetry.org/docs/configuration/#virtualenvsin-project), yes.

You mean `make install` not working?

**Comment by hagenw** [comment]
I started now from scratch.

I made sure that no `.venv` folder existed and no virtual environment was activated and then run:
```bash
$ make install
$ poetry install
$ source .venv/bin/activate
$ python -m pytest
```
And it worked.

So, I guess the guide in `CONTRIBUTING.md` is correct.
Will close this issue.
