### ISSUE TITLE
Colab "!pip install omnizart" it has been installed for several hours!

### ISSUE THREAD

**Issue by Landers125** [Music-and-Culture-Technology-Lab/omnizart#46]

**Comment by Landers125** [comment]
need to change to !pip install --use-deprecated=legacy-resolver omnizart

**Comment by Landers125** [comment]
downgrade!))

**Comment by PSCM** [comment]
@Landers125 , I also have this problem!

**Comment by Landers125** [comment]
![image](https://user-images.githubusercontent.com/94287585/143497608-6895a3dd-f1b8-4771-92f2-49f4a23bdd46.png)

**Comment by BreezeWhite** [comment]
Hi, I've updated the installation scripts. It's now using `git clone` and `pip install .` to install omnizart. And I also added `pip install -U pip` before installing anything. These changes should fix the problems.

Another change is replace `youtube-dl` with `yt-dlp` for downloading sources from Youtube, since the former hasn't updated for a long time and could probably fail to download anything.
